# Generated by Django 5.2 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('creator', 'Creator'), ('business_owner', 'Business Owner'), ('agency_owner', 'Agency Owner'), ('social_media_manager', 'Social Media Manager')], max_length=50, null=True),
        ),
    ]
