# Generated by Django 5.2 on 2026-06-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnboardingData',
        ),
    ]
