# Generated by Django 5.2 on 2026-06-05 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_onboardingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('marketing', 'Marketing'), ('ecommerce', 'Ecommerce'), ('real_estate', 'Real Estate'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('other', 'Other')], max_length=100, null=True)),
                ('posting_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_platform', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('x', 'X'), ('youtube', 'YouTube')], max_length=100, null=True)),
                ('team_size', models.CharField(blank=True, choices=[('just_me', 'Just Me'), ('small_team', 'Small Team'), ('medium_team', 'Medium Team'), ('large_team', 'Large Team')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_user_brand_name'), models.UniqueConstraint(fields=('user', 'is_default'), name='unique_user_default_brand')],
            },
        ),
    ]
