# Generated by Django 5.2 on 2026-08-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_brand'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brand',
            name='unique_user_default_brand',
        ),
        migrations.AddField(
            model_name='user',
            name='active_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.brand'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_user_default_brand'),
        ),
    ]
