# Generated by Django 5.2 on 2026-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_brand_unique_user_default_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
