exclude: "^docs/|/migrations/"
default_stages: [pre-push]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]  # Use the latest Python syntax features

    # This compiles pyproject.toml into requirements.txt automatically on commit
- repo: https://github.com/astral-sh/uv-pre-commit
    rev: v0.1.0 
    hooks:
    -   id: uv-pre-commit
        args: [pyproject.toml, -o, requirements.txt]

repo: local
    hooks:
      - id: uv-compile-and-commit
        name: Auto-stage all modified files and commit
        entry: >
          cmd.exe /c "
          git diff --quiet || (
            git add -u &&
            git commit -m 'fix: linting check'
          )
          "
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]