# Generated by Django 5.2 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0002_brand_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('marketing', 'Marketing'), ('ecommerce', 'Ecommerce'), ('real_estate', 'Real Estate'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='primary_platform',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('x', 'X'), ('youtube', 'YouTube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='team_size',
            field=models.CharField(blank=True, choices=[('just_me', 'Just Me'), ('small_team', 'Small Team'), ('medium_team', 'Medium Team'), ('large_team', 'Large Team')], max_length=100, null=True),
        ),
    ]
