# Generated by Django 5.2 on 2026-06-05 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0003_brand_onboarding_choices'),
        ('users', '0006_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='users.brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
