# Generated by Django 5.2 on 2026-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0004_alter_socialaccount_brand_delete_brand'),
        ('users', '0006_brand'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='unique_brand_social_account',
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='expires_at',
            new_name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='account_type',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_name',
            field=models.CharField(blank=True, default='', help_text='The username or page name associated with the social account (e.g., @username for Instagram or page name for Facebook).', max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='external_id',
            field=models.CharField(default='dfasfsdfsd33d', help_text='The unique identifier for the social account on the platform.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], default='youtube', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('brand', 'platform'), name='unique_brand_social_account'),
        ),
    ]
