# Generated by Django 5.2 on 2026-07-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0005_remove_socialaccount_unique_brand_social_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=50),
        ),
    ]
