# Generated by Copilot on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0005_remove_socialaccount_unique_brand_social_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
