# Generated by Django 5.2 on 2026-09-10 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0006_socialaccount_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='last_connected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when this account was most recently connected or re-authenticated.'),
        ),
    ]
