# Generated by Django 5.2 on 2026-06-14 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('video_r2_key', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading to Platform'), ('posted', 'Posted Successfully'), ('failed', 'Posting Failed')], default='pending', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, default='', help_text='The post/video ID returned by the platform API.', max_length=255)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the post failed.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_posts', to='users.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='content_con_user_id_16e099_idx'), models.Index(fields=['brand', 'status'], name='content_con_brand_i_f59c85_idx')],
            },
        ),
    ]
