# Generated by Django 5.2 on 2026-06-14 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0006_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPostPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading to Platform'), ('posted', 'Posted Successfully'), ('failed', 'Posting Failed')], default='pending', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, default='', help_text='The post/video ID returned by the platform API.', max_length=255)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if this platform post failed.')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.RemoveIndex(
            model_name='contentpost',
            name='content_con_user_id_16e099_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentpost',
            name='content_con_brand_i_f59c85_idx',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='platform_post_id',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='status',
        ),
        migrations.AddIndex(
            model_name='contentpost',
            index=models.Index(fields=['user'], name='content_con_user_id_e3152d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpost',
            index=models.Index(fields=['brand'], name='content_con_brand_i_fc8790_idx'),
        ),
        migrations.AddField(
            model_name='contentpostplatform',
            name='content_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_entries', to='content.contentpost'),
        ),
        migrations.AddConstraint(
            model_name='contentpostplatform',
            constraint=models.UniqueConstraint(fields=('content_post', 'platform'), name='unique_content_post_platform'),
        ),
    ]
