# Generated by Django 5.2 on 2026-06-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentpostplatform_and_more'),
    ]

    operations = [
        # Rename video_r2_key to media_r2_key
        migrations.RenameField(
            model_name='contentpost',
            old_name='video_r2_key',
            new_name='media_r2_key',
        ),
        # Add content_type field
        migrations.AddField(
            model_name='contentpost',
            name='content_type',
            field=models.CharField(
                choices=[('video', 'Video'), ('photo', 'Photo')],
                default='video',
                max_length=10,
            ),
        ),
    ]
