# Generated by Django 5.2 on 2026-06-17 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_content_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpost',
            name='media_r2_key',
        ),
        migrations.AlterField(
            model_name='contentpostplatform',
            name='platform_post_id',
            field=models.CharField(blank=True, default='', help_text='The post/media ID returned by the platform API.', max_length=255),
        ),
        migrations.CreateModel(
            name='ContentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('r2_key', models.CharField(max_length=512)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='content.contentpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
