# Generated by Django 5.2 on 2026-07-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_contentpost_media_r2_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpost',
            old_name='description',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='title',
        ),
        migrations.AddField(
            model_name='contentpostplatform',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='The resolved caption/description for this specific platform.'),
        ),
        migrations.AddField(
            model_name='contentpostplatform',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The resolved title/caption for this specific platform.', max_length=255),
        ),
    ]
