# Generated by Django 5.2 on 2026-07-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_description_contentpost_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('text', 'Text')], default='video', max_length=10),
        ),
    ]
