# Generated by Django 5.2 on 2026-07-13 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_contentpost_content_type'),
        ('users', '0006_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contentpostplatform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('uploading', 'Uploading to Platform'), ('posted', 'Posted Successfully'), ('failed', 'Posting Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contentpost',
            index=models.Index(fields=['scheduled_at'], name='content_con_schedul_59caad_idx'),
        ),
    ]
