# Generated by Django 5.2 on 2026-07-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentpost_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='thumbnail_r2_key',
            field=models.CharField(blank=True, default='', help_text='The Cloudflare R2 key for the custom video thumbnail image.', max_length=512),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='video_thumbnail_offset',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The selected frame offset in milliseconds from the start of the video.', null=True),
        ),
    ]
