# Generated by Django 5.2 on 2026-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentpost_thumbnail_r2_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpostplatform',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
