# Generated by Django 5.2 on 2026-08-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contentpostplatform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpostplatform',
            name='post_url',
            field=models.URLField(blank=True, default='', help_text='The public, clickable URL of the published post.', max_length=500),
        ),
        migrations.AlterField(
            model_name='contentpostplatform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('uploading', 'Uploading to Platform'), ('processing', 'Processing on Platform'), ('posted', 'Posted Successfully'), ('failed', 'Posting Failed')], default='pending', max_length=20),
        ),
    ]
