# Generated by Django 5.2 on 2026-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_contentpostplatform_post_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='email_notified_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp when the post completion email notification was sent.', null=True),
        ),
    ]
